version: 0.2

phases:

  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 947681381905.dkr.ecr.ap-south-1.amazonaws.com
      - docker pull 947681381905.dkr.ecr.ap-south-1.amazonaws.com/gem-cpbe-demo:latest

  build:
    commands:     
      - docker build -t gem-cpbe-demo .
      - docker tag gem-cpbe-demo:latest 947681381905.dkr.ecr.ap-south-1.amazonaws.com/gem-cpbe-demo:latest

  post_build:
    commands:
      - docker push 947681381905.dkr.ecr.ap-south-1.amazonaws.com/gem-cpbe-demo:latest
      - kubectl apply -f Deployment.yaml
      - kubectl rollout restart -f Deployment.yaml
