apiVersion: apps/v1
kind: Deployment
metadata:
  name: gem-cpbe-demo-deployment
  namespace: gem-cpbe
  labels:
    app: gem-cpbe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gem-cpbe-demo
  template:
    metadata:
      labels:
        app: gem-cpbe-demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: gem-cpbe-demo
        image: 947681381905.dkr.ecr.ap-south-1.amazonaws.com/gem-cpbe-demo:latest
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: Always
